import { TemplateAnalysis } from '@/types';

export interface StaticTemplateDefinition {
  id: string;
  name: string;
  description: string;
  badge: string;
  category: 'Executive' | 'Corporate' | 'Tech' | 'Creative' | 'Minimalist' | 'Academic';
  colorPreview: string[];
  analysis: TemplateAnalysis;
  defaultSingleton: Record<string, string>;
  defaultEntries: Record<string, Array<Record<string, string>>>;
}

export const STATIC_TEMPLATES: StaticTemplateDefinition[] = [
  // 1. PLUM EXECUTIVE (Korina Villanueva - Image 1 Right)
  {
    id: 'modern-executive',
    name: 'Modern Executive (Plum)',
    description: 'Deep plum header band with soft lavender sidebar, solid square heading badges, and right-aligned dates.',
    badge: 'Popular',
    category: 'Executive',
    colorPreview: ['#4c1728', '#f5f0f3', '#4c1728', '#1a1a1a'],
    analysis: {
      templateName: 'Modern Executive (Plum)',
      description: 'Plum header band and soft lavender sidebar layout with icon badges',
      confidence: 0.98,
      layout: {
        type: 'sidebar-left',
        headerPlacement: 'main-column',
        columns: [
          { id: 'sidebar', width: 0.3 },
          { id: 'main', width: 0.7 },
        ],
        photo: {
          included: true,
          position: 'sidebar',
          shape: 'circle',
          size: 'medium',
        },
        page: {
          widthMm: 210,
          heightMm: 297,
          margins: { top: 6, right: 7, bottom: 6, left: 7 },
        },
        geometry: {
          orientation: 'portrait',
          sidebarWidth: 0.3,
          mainWidth: 0.7,
          gap: 0,
          verticalGap: 11,
          headerHeight: 90,
        },
        orderedSections: [
          'personal',
          'contact',
          'softSkills',
          'techSkills',
          'languages',
          'profile',
          'experience',
          'education',
          'projects',
          'achievements',
          'references',
        ],
        sidebarSections: ['contact', 'softSkills', 'techSkills', 'languages'],
        placements: [
          { sectionId: 'contact', column: 'sidebar', order: 0 },
          { sectionId: 'softSkills', column: 'sidebar', order: 1 },
          { sectionId: 'techSkills', column: 'sidebar', order: 2 },
          { sectionId: 'languages', column: 'sidebar', order: 3 },
          { sectionId: 'profile', column: 'main', order: 0 },
          { sectionId: 'experience', column: 'main', order: 1 },
          { sectionId: 'education', column: 'main', order: 2 },
          { sectionId: 'projects', column: 'main', order: 3 },
          { sectionId: 'achievements', column: 'main', order: 4 },
          { sectionId: 'references', column: 'main', order: 5 },
        ],
      },
      style: {
        primaryColor: '#4c1728',
        secondaryColor: '#f5f0f3',
        accentColor: '#4c1728',
        backgroundColor: '#ffffff',
        textColor: '#222222',
        fontFamily: 'Arial, sans-serif',
        headerStyle: 'left-aligned',
        sectionDivider: 'line',
        nameSize: 22,
        headingSize: 12,
        bodySize: 9.5,
        theme: {
          headerBackground: '#4c1728',
          sidebarBackground: '#f5f0f3',
          mainBackground: '#ffffff',
          headingColor: '#4c1728',
          textColor: '#2b2b2b',
          borderColor: '#4c1728',
          iconColor: '#4c1728',
        },
        typography: {
          name: { family: 'Arial, sans-serif', weight: 700, size: 22, letterSpacing: 1.5, textTransform: 'uppercase' },
          jobTitle: { family: 'Arial, sans-serif', weight: 600, size: 12.5, letterSpacing: 1.2, textTransform: 'uppercase' },
          sectionHeading: { family: 'Arial, sans-serif', weight: 700, size: 12, letterSpacing: 1.2, textTransform: 'uppercase' },
          sidebarHeading: { family: 'Arial, sans-serif', weight: 700, size: 11, letterSpacing: 1.2, textTransform: 'uppercase' },
          body: { family: 'Arial, sans-serif', weight: 400, size: 9.5, lineHeight: 1.4 },
          sidebarText: { family: 'Arial, sans-serif', weight: 400, size: 9, lineHeight: 1.35 },
        },
        componentStyle: {
          headingVariant: 'underline',
          bulletStyle: 'dot',
          timeline: false,
          icons: true,
          headerBackground: true,
        },
      },
      sections: [
        { id: 'personal', name: 'Personal Details', description: 'Name, title, and portrait', repeatable: false },
        { id: 'contact', name: 'Contact', description: 'Phone, email, and address', repeatable: false },
        { id: 'softSkills', name: 'Soft Skills', description: 'Core interpersonal strengths', repeatable: false },
        { id: 'techSkills', name: 'Tech Skills', description: 'Software and technical abilities', repeatable: false },
        { id: 'languages', name: 'Languages', description: 'Language proficiencies', repeatable: false },
        { id: 'profile', name: 'Profile', description: 'Professional background summary', repeatable: false },
        { id: 'experience', name: 'Work Experience', description: 'Employment history and accomplishments', repeatable: true },
        { id: 'education', name: 'Education', description: 'Academic credentials', repeatable: true },
        { id: 'projects', name: 'Projects', description: 'Key initiatives and accomplishments', repeatable: true },
        { id: 'achievements', name: 'Achievements & Hackathons', description: 'Honors and programs', repeatable: true },
        { id: 'references', name: 'References', description: 'Professional contacts', repeatable: true },
      ],
      fields: [
        { id: 'fullName', label: 'Full Name', type: 'text', required: true, section: 'personal' },
        { id: 'jobTitle', label: 'Professional Title', type: 'text', required: true, section: 'personal' },
        { id: 'phone', label: 'Phone', type: 'phone', required: true, section: 'contact' },
        { id: 'email', label: 'Email Address', type: 'email', required: true, section: 'contact' },
        { id: 'address', label: 'Address', type: 'text', required: false, section: 'contact' },
        { id: 'softSkillsList', label: 'Soft Skills (one per line)', type: 'textarea', required: false, section: 'softSkills' },
        { id: 'techSkillsList', label: 'Tech Skills (one per line)', type: 'textarea', required: false, section: 'techSkills' },
        { id: 'languagesList', label: 'Languages (one per line)', type: 'textarea', required: false, section: 'languages' },
        { id: 'summary', label: 'Professional Summary', type: 'textarea', required: false, section: 'profile' },
        { id: 'role', label: 'Position / Role', type: 'text', required: true, section: 'experience' },
        { id: 'company', label: 'Company / Organization', type: 'text', required: true, section: 'experience' },
        { id: 'expPeriod', label: 'Period (e.g. 2029 - PRESENT)', type: 'text', required: false, section: 'experience' },
        { id: 'responsibilities', label: 'Responsibilities & Key Achievements', type: 'textarea', required: false, section: 'experience' },
        { id: 'degree', label: 'Degree / Program', type: 'text', required: true, section: 'education' },
        { id: 'institution', label: 'University / School', type: 'text', required: true, section: 'education' },
        { id: 'eduYear', label: 'Graduation Year / Period', type: 'text', required: false, section: 'education' },
        { id: 'grade', label: 'GPA / Honors', type: 'text', required: false, section: 'education' },
        { id: 'projectName', label: 'Project Title', type: 'text', required: true, section: 'projects' },
        { id: 'projectDesc', label: 'Description & Outcomes', type: 'textarea', required: false, section: 'projects' },
        { id: 'achievementTitle', label: 'Award / Program Name', type: 'text', required: true, section: 'achievements' },
        { id: 'achievementDesc', label: 'Organization / Details', type: 'text', required: false, section: 'achievements' },
        { id: 'refName', label: 'Full Name & Title', type: 'text', required: true, section: 'references' },
        { id: 'refDetails', label: 'Organization & Contact', type: 'text', required: false, section: 'references' },
      ],
    },
    defaultSingleton: {
      fullName: 'Korina Villanueva',
      jobTitle: 'Computer Science Student',
      phone: '+123-456-7890',
      email: 'hello@reallygreatsite.com',
      address: '123 Anywhere St., Any City',
      softSkillsList: 'Teamwork\nTime Management\nLeadership\nEffective Communication\nCritical Thinking',
      techSkillsList: 'Python (Expert)\nJava (Expert)\nC++ (Intermediate)\nData Structures & Algorithms\nSQL, MySQL\nMachine Learning\nWeb Development',
      languagesList: 'English (Fluent)\nFrench (Fluent)\nGerman (Basic)',
      summary:
        'Motivated and detail-oriented Computer Science student with a strong foundation in software engineering, algorithms, and full-stack web development. Experienced in building responsive web platforms and real-time networked applications with modern tech stacks.',
    },
    defaultEntries: {
      experience: [
        {
          role: 'Junior Software Engineer',
          company: 'Borcelle Studio | San Francisco, CA',
          expPeriod: '2029 - PRESENT',
          responsibilities:
            'Developed responsive web applications using React, Next.js, and TypeScript.\nCollaborated with product designers to implement pixel-perfect user interfaces.\nIntegrated RESTful APIs and improved client-side rendering performance.',
        },
      ],
      education: [
        {
          degree: 'Bachelor of Computer Science',
          institution: 'School of Science | Wardiere University',
          eduYear: '2029 - 2032',
          grade: 'GPA: 3.8 / 4.0',
        },
        {
          degree: 'High School Diploma',
          institution: 'Borcelle High School',
          eduYear: '2025 - 2029',
          grade: 'GPA: 3.9 / 4.0',
        },
      ],
      projects: [
        {
          projectName: 'E-commerce Platform Development',
          projectDesc:
            'Led the development of a comprehensive e-commerce platform for a retail company, including features such as product listings, shopping cart, payment gateway integration, and order management.\nTechnologies Used: React, Node.js, MongoDB, Express, Stripe API.',
        },
        {
          projectName: 'Real-time Chat Application',
          projectDesc:
            'Developed a real-time chat application enabling users to send instant messages, create group chats, and share multimedia content with low latency.\nTechnologies Used: Socket.io, Node.js, Express, MongoDB.',
        },
      ],
      achievements: [
        {
          achievementTitle: 'Academic Excellence Award',
          achievementDesc: 'Recognized for academic excellence and maintaining a GPA of 3.8/4.0 in my college.',
        },
        {
          achievementTitle: 'Top 5% Hackathon Finalist',
          achievementDesc: 'Ranked in the top 5% out of 500 participants in a machine learning hackathon.',
        },
        {
          achievementTitle: 'Best Project Prize',
          achievementDesc: 'Won first prize for the best project in a renowned tech hackathon for my Sustainable Shopping Assistant project.',
        },
      ],
      references: [
        {
          refName: 'Prof. Julian Reynolds (PhD)',
          refDetails: 'Chair of Computer Science | Wardiere University | j.reynolds@wardiere.edu',
        },
        {
          refName: 'Dr. Elena Rostova',
          refDetails: 'Associate Professor | Wardiere University | Phone: +123-456-7891',
        },
      ],
    },
  },

  // 2. NAVY PROFESSIONAL (Richard Sanchez - Image 2 Left)
  {
    id: 'navy-professional',
    name: 'Navy Professional',
    description: 'Full-height deep navy sidebar with white icons, clean white main column, and work experience timeline dots.',
    badge: 'Recruiter Choice',
    category: 'Corporate',
    colorPreview: ['#142b42', '#ffffff', '#142b42', '#2563eb'],
    analysis: {
      templateName: 'Navy Professional',
      description: 'Deep navy sidebar layout with timeline work experience',
      confidence: 0.97,
      layout: {
        type: 'sidebar-left',
        headerPlacement: 'main-column',
        columns: [
          { id: 'sidebar', width: 0.32 },
          { id: 'main', width: 0.68 },
        ],
        photo: {
          included: true,
          position: 'sidebar',
          shape: 'circle',
          size: 'large',
        },
        page: {
          widthMm: 210,
          heightMm: 297,
          margins: { top: 6, right: 7, bottom: 6, left: 7 },
        },
        geometry: {
          orientation: 'portrait',
          sidebarWidth: 0.32,
          mainWidth: 0.68,
          gap: 0,
          verticalGap: 11,
        },
        orderedSections: [
          'personal',
          'contact',
          'education',
          'skills',
          'languages',
          'profile',
          'experience',
          'references',
        ],
        sidebarSections: ['contact', 'education', 'skills', 'languages'],
        placements: [
          { sectionId: 'contact', column: 'sidebar', order: 0 },
          { sectionId: 'education', column: 'sidebar', order: 1 },
          { sectionId: 'skills', column: 'sidebar', order: 2 },
          { sectionId: 'languages', column: 'sidebar', order: 3 },
          { sectionId: 'profile', column: 'main', order: 0 },
          { sectionId: 'experience', column: 'main', order: 1 },
          { sectionId: 'references', column: 'main', order: 2 },
        ],
      },
      style: {
        primaryColor: '#142b42',
        secondaryColor: '#f8fafc',
        accentColor: '#2563eb',
        backgroundColor: '#ffffff',
        textColor: '#334155',
        fontFamily: 'Arial, sans-serif',
        headerStyle: 'left-aligned',
        sectionDivider: 'line',
        nameSize: 24,
        headingSize: 12.5,
        bodySize: 9.5,
        theme: {
          headerBackground: undefined,
          sidebarBackground: '#142b42',
          mainBackground: '#ffffff',
          headingColor: '#142b42',
          sidebarHeadingColor: '#ffffff',
          textColor: '#334155',
          borderColor: '#142b42',
          iconColor: '#142b42',
        },
        typography: {
          name: { family: 'Arial, sans-serif', weight: 800, size: 24, letterSpacing: 1.5, textTransform: 'uppercase' },
          jobTitle: { family: 'Arial, sans-serif', weight: 600, size: 13, letterSpacing: 1.5, textTransform: 'uppercase' },
          sectionHeading: { family: 'Arial, sans-serif', weight: 700, size: 12.5, letterSpacing: 1.5, textTransform: 'uppercase' },
          sidebarHeading: { family: 'Arial, sans-serif', weight: 700, size: 12, letterSpacing: 1.5, textTransform: 'uppercase' },
          body: { family: 'Arial, sans-serif', weight: 400, size: 9.5, lineHeight: 1.4 },
          sidebarText: { family: 'Arial, sans-serif', weight: 400, size: 9, lineHeight: 1.35 },
        },
        componentStyle: {
          headingVariant: 'underline',
          bulletStyle: 'dot',
          timeline: true,
          icons: true,
          headerBackground: false,
        },
      },
      sections: [
        { id: 'personal', name: 'Personal Details', description: 'Name and professional title', repeatable: false },
        { id: 'contact', name: 'Contact', description: 'Phone, email, address, website', repeatable: false },
        { id: 'education', name: 'Education', description: 'University and degrees', repeatable: true },
        { id: 'skills', name: 'Skills', description: 'Core professional competencies', repeatable: false },
        { id: 'languages', name: 'Languages', description: 'Language proficiencies', repeatable: false },
        { id: 'profile', name: 'Profile', description: 'Professional executive summary', repeatable: false },
        { id: 'experience', name: 'Work Experience', description: 'Employment history and achievements', repeatable: true },
        { id: 'references', name: 'Reference', description: 'Endorsements from executives', repeatable: true },
      ],
      fields: [
        { id: 'fullName', label: 'Full Name', type: 'text', required: true, section: 'personal' },
        { id: 'jobTitle', label: 'Professional Title', type: 'text', required: true, section: 'personal' },
        { id: 'phone', label: 'Phone', type: 'phone', required: true, section: 'contact' },
        { id: 'email', label: 'Email', type: 'email', required: true, section: 'contact' },
        { id: 'address', label: 'Address', type: 'text', required: false, section: 'contact' },
        { id: 'website', label: 'Website', type: 'text', required: false, section: 'contact' },
        { id: 'degree', label: 'Degree / Program', type: 'text', required: true, section: 'education' },
        { id: 'institution', label: 'University', type: 'text', required: true, section: 'education' },
        { id: 'eduYear', label: 'Period / Year', type: 'text', required: false, section: 'education' },
        { id: 'grade', label: 'GPA / Honors', type: 'text', required: false, section: 'education' },
        { id: 'skillsList', label: 'Skills (one per line)', type: 'textarea', required: false, section: 'skills' },
        { id: 'languagesList', label: 'Languages (one per line)', type: 'textarea', required: false, section: 'languages' },
        { id: 'summary', label: 'Profile Summary', type: 'textarea', required: false, section: 'profile' },
        { id: 'role', label: 'Position / Role', type: 'text', required: true, section: 'experience' },
        { id: 'company', label: 'Company / Studio', type: 'text', required: true, section: 'experience' },
        { id: 'expPeriod', label: 'Period (e.g. 2030 - PRESENT)', type: 'text', required: false, section: 'experience' },
        { id: 'responsibilities', label: 'Responsibilities & Impact', type: 'textarea', required: false, section: 'experience' },
        { id: 'refName', label: 'Name & Title', type: 'text', required: true, section: 'references' },
        { id: 'refContact', label: 'Company & Contact Info', type: 'text', required: false, section: 'references' },
      ],
    },
    defaultSingleton: {
      fullName: 'Richard Sanchez',
      jobTitle: 'Marketing Manager',
      phone: '+123-456-7890',
      email: 'hello@reallygreatsite.com',
      address: '123 Anywhere St., Any City',
      website: 'www.reallygreatsite.com',
      skillsList: 'Project Management\nPublic Relations\nTeamwork\nTime Management\nLeadership\nEffective Communication\nCritical Thinking',
      languagesList: 'English (Fluent)\nFrench (Fluent)\nGerman (Basics)\nSpanish (Intermediate)',
      summary:
        'Results-driven Marketing Manager with 8+ years developing and executing high-impact marketing campaigns that drive brand awareness, revenue growth, and market engagement. Skilled in cross-functional team leadership, budget allocation, and multi-channel content strategy.',
    },
    defaultEntries: {
      education: [
        {
          degree: 'Master of Business Management',
          institution: 'Wardiere University',
          eduYear: '2029 - 2030',
        },
        {
          degree: 'Bachelor of Business',
          institution: 'Wardiere University',
          eduYear: '2025 - 2029',
          grade: 'GPA: 3.8 / 4.0',
        },
      ],
      experience: [
        {
          role: 'Marketing Manager & Specialist',
          company: 'Borcelle Studio',
          expPeriod: '2030 - PRESENT',
          responsibilities:
            'Develop and execute comprehensive marketing strategies and campaigns that align with the company’s goals and objectives.\nLead, mentor, and manage a high-performing marketing team, fostering a collaborative and results-driven work environment.\nMonitor brand consistency across marketing channels and materials.',
        },
        {
          role: 'Marketing Manager & Specialist',
          company: 'Fauget Studio',
          expPeriod: '2025 - 2029',
          responsibilities:
            'Create and manage the marketing budget, ensuring efficient allocation of resources and optimizing ROI.\nOversee market research to identify emerging trends, customer needs, and competitor strategies.',
        },
        {
          role: 'Marketing Manager & Specialist',
          company: 'Studio Shodwe',
          expPeriod: '2024 - 2025',
          responsibilities:
            'Develop and maintain strong relationships with partners, agencies, and vendors to support marketing initiatives.\nMonitor and maintain brand consistency across all marketing channels and materials.',
        },
      ],
      references: [
        {
          refName: 'Estelle Darcy',
          refContact: 'Wardiere Inc. / CTO | Phone: 123-456-7890 | Email: hello@reallygreatsite.com',
        },
        {
          refName: 'Harper Richard',
          refContact: 'Wardiere Inc. / CEO | Phone: 123-456-7890 | Email: hello@reallygreatsite.com',
        },
      ],
    },
  },

  // 3. CHARCOAL PROFESSIONAL (Dani Martinez - Image 3 Left)
  {
    id: 'charcoal-professional',
    name: 'Charcoal Professional',
    description: 'Solid dark charcoal sidebar with about bio, skills, awards, and clean two-column main section.',
    badge: 'Executive',
    category: 'Executive',
    colorPreview: ['#28292c', '#ffffff', '#28292c', '#4b5563'],
    analysis: {
      templateName: 'Charcoal Professional',
      description: 'Charcoal sidebar resume with awards and side-by-side references',
      confidence: 0.96,
      layout: {
        type: 'sidebar-left',
        headerPlacement: 'main-column',
        columns: [
          { id: 'sidebar', width: 0.32 },
          { id: 'main', width: 0.68 },
        ],
        photo: {
          included: true,
          position: 'sidebar',
          shape: 'circle',
          size: 'large',
        },
        page: {
          widthMm: 210,
          heightMm: 297,
          margins: { top: 6, right: 7, bottom: 6, left: 7 },
        },
        geometry: {
          orientation: 'portrait',
          sidebarWidth: 0.32,
          mainWidth: 0.68,
          gap: 0,
          verticalGap: 12,
        },
        orderedSections: [
          'personal',
          'aboutMe',
          'contact',
          'skills',
          'language',
          'awards',
          'education',
          'experience',
          'references',
        ],
        sidebarSections: ['aboutMe', 'contact', 'skills', 'language', 'awards'],
        placements: [
          { sectionId: 'aboutMe', column: 'sidebar', order: 0 },
          { sectionId: 'contact', column: 'sidebar', order: 1 },
          { sectionId: 'skills', column: 'sidebar', order: 2 },
          { sectionId: 'language', column: 'sidebar', order: 3 },
          { sectionId: 'awards', column: 'sidebar', order: 4 },
          { sectionId: 'education', column: 'main', order: 0 },
          { sectionId: 'experience', column: 'main', order: 1 },
          { sectionId: 'references', column: 'main', order: 2 },
        ],
      },
      style: {
        primaryColor: '#28292c',
        secondaryColor: '#f3f4f6',
        accentColor: '#374151',
        backgroundColor: '#ffffff',
        textColor: '#374151',
        fontFamily: 'Arial, sans-serif',
        headerStyle: 'left-aligned',
        sectionDivider: 'line',
        nameSize: 26,
        headingSize: 13,
        bodySize: 9.5,
        theme: {
          headerBackground: undefined,
          sidebarBackground: '#28292c',
          mainBackground: '#ffffff',
          headingColor: '#1f2937',
          sidebarHeadingColor: '#ffffff',
          textColor: '#374151',
          borderColor: '#28292c',
          iconColor: '#28292c',
        },
        typography: {
          name: { family: 'Arial, sans-serif', weight: 800, size: 26, letterSpacing: 1, textTransform: 'uppercase' },
          jobTitle: { family: 'Arial, sans-serif', weight: 600, size: 13, letterSpacing: 1.5, textTransform: 'uppercase' },
          sectionHeading: { family: 'Arial, sans-serif', weight: 700, size: 13, letterSpacing: 1.5, textTransform: 'uppercase' },
          sidebarHeading: { family: 'Arial, sans-serif', weight: 700, size: 12, letterSpacing: 1.5, textTransform: 'uppercase' },
          body: { family: 'Arial, sans-serif', weight: 400, size: 9.5, lineHeight: 1.4 },
          sidebarText: { family: 'Arial, sans-serif', weight: 400, size: 9, lineHeight: 1.35 },
        },
        componentStyle: {
          headingVariant: 'underline',
          bulletStyle: 'dot',
          timeline: false,
          icons: true,
          headerBackground: false,
        },
      },
      sections: [
        { id: 'personal', name: 'Personal Details', description: 'Name and role', repeatable: false },
        { id: 'aboutMe', name: 'About Me', description: 'Brief bio in sidebar', repeatable: false },
        { id: 'contact', name: 'Contact', description: 'Phone, email, address', repeatable: false },
        { id: 'skills', name: 'Skills', description: 'Core competencies', repeatable: false },
        { id: 'language', name: 'Language', description: 'Language fluency', repeatable: false },
        { id: 'awards', name: 'Awards', description: 'Honors and recognitions', repeatable: true },
        { id: 'education', name: 'Education', description: 'Degrees and academic history', repeatable: true },
        { id: 'experience', name: 'Experience', description: 'Professional work roles', repeatable: true },
        { id: 'references', name: 'References', description: 'Endorsements', repeatable: true },
      ],
      fields: [
        { id: 'fullName', label: 'Full Name', type: 'text', required: true, section: 'personal' },
        { id: 'jobTitle', label: 'Job Title', type: 'text', required: true, section: 'personal' },
        { id: 'aboutBio', label: 'Bio / Summary', type: 'textarea', required: false, section: 'aboutMe' },
        { id: 'phone', label: 'Phone', type: 'phone', required: true, section: 'contact' },
        { id: 'email', label: 'Email', type: 'email', required: true, section: 'contact' },
        { id: 'address', label: 'Address', type: 'text', required: false, section: 'contact' },
        { id: 'skillsList', label: 'Skills (one per line)', type: 'textarea', required: false, section: 'skills' },
        { id: 'languagesList', label: 'Languages (one per line)', type: 'textarea', required: false, section: 'language' },
        { id: 'awardName', label: 'Award Title', type: 'text', required: true, section: 'awards' },
        { id: 'awardDetails', label: 'Organization & Date', type: 'text', required: false, section: 'awards' },
        { id: 'degree', label: 'Degree / Program', type: 'text', required: true, section: 'education' },
        { id: 'university', label: 'University / College', type: 'text', required: true, section: 'education' },
        { id: 'eduDates', label: 'Dates (e.g. 2020 - 2023)', type: 'text', required: false, section: 'education' },
        { id: 'role', label: 'Job Role', type: 'text', required: true, section: 'experience' },
        { id: 'companyLocation', label: 'Company & Location', type: 'text', required: true, section: 'experience' },
        { id: 'expDates', label: 'Dates (e.g. 2020 - 2022)', type: 'text', required: false, section: 'experience' },
        { id: 'expDesc', label: 'Key Contributions', type: 'textarea', required: false, section: 'experience' },
        { id: 'refName', label: 'Full Name & Title', type: 'text', required: true, section: 'references' },
        { id: 'refContact', label: 'Organization & Phone', type: 'text', required: false, section: 'references' },
      ],
    },
    defaultSingleton: {
      fullName: 'Dani Martinez',
      jobTitle: 'Marketing Manager',
      aboutBio:
        'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum sit amet quam rhoncus, egestas dui eget, malesuada justo. Ut aliquam augue dui.',
      phone: '+123-456-7890',
      email: 'hello@reallygreatsite.com',
      address: '123 Anywhere St., Any City',
      skillsList: 'Management Skills\nCreativity\nDigital Marketing\nNegotiation\nCritical Thinking\nLeadership',
      languagesList: 'English (Fluent)\nGermany (Basic)',
    },
    defaultEntries: {
      awards: [
        {
          awardName: 'The Best Employee of the Year',
          awardDetails: 'Oct 2019 | Ingoude Company',
        },
      ],
      education: [
        {
          degree: 'Bachelor of Business Management',
          university: 'Borcelle University',
          eduDates: '2020 - 2023',
        },
        {
          degree: 'Master of Business Management',
          university: 'Borcelle University',
          eduDates: '2016 - 2020',
        },
      ],
      experience: [
        {
          role: 'Marketing Manager',
          companyLocation: 'Arowwai Industries | Sydney - Australia',
          expDates: '2020 - 2022',
          expDesc:
            'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam pharetra in lorem at laoreet. Donec hendrerit libero eget est tempor, quis tempus arcu elementum.',
        },
        {
          role: 'Marketing Specialist',
          companyLocation: 'Wardiere Inc. | Sydney - Australia',
          expDates: '2016 - 2020',
          expDesc:
            'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam pharetra in lorem at laoreet. Donec hendrerit libero eget est tempor, quis tempus arcu elementum.',
        },
        {
          role: 'Studio Associate',
          companyLocation: 'Studio Showde | Sydney - Australia',
          expDates: '2010 - 2015',
          expDesc:
            'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam pharetra in lorem at laoreet. Donec hendrerit libero eget est tempor, quis tempus arcu elementum.',
        },
      ],
      references: [
        {
          refName: 'Bailey Dupont',
          refContact: 'Wardiere Inc. / CEO | Phone: 123-456-7890 | Email: hello@reallygreatsite.com',
        },
        {
          refName: 'Harumi Kobayashi',
          refContact: 'Wardiere Inc. / CEO | Phone: 123-456-7890 | Email: hello@reallygreatsite.com',
        },
      ],
    },
  },

  // 4. MODERN SLATE TIMELINE (Richard Sanchez - Image 2 Right)
  {
    id: 'slate-timeline',
    name: 'Modern Slate Timeline',
    description: 'Dark slate header band with cool gray sidebar, timeline tree connecting work milestones, and circular photo.',
    badge: 'Timeline Pro',
    category: 'Tech',
    colorPreview: ['#2c3848', '#e8edf2', '#ffffff', '#2c3848'],
    analysis: {
      templateName: 'Modern Slate Timeline',
      description: 'Slate header band with light sidebar and connected timeline nodes',
      confidence: 0.97,
      layout: {
        type: 'sidebar-left',
        headerPlacement: 'top-full-width',
        columns: [
          { id: 'sidebar', width: 0.32 },
          { id: 'main', width: 0.68 },
        ],
        photo: {
          included: true,
          position: 'sidebar',
          shape: 'circle',
          size: 'large',
        },
        page: {
          widthMm: 210,
          heightMm: 297,
          margins: { top: 6, right: 7, bottom: 6, left: 7 },
        },
        geometry: {
          orientation: 'portrait',
          sidebarWidth: 0.32,
          mainWidth: 0.68,
          gap: 0,
          verticalGap: 11,
          headerHeight: 85,
        },
        orderedSections: [
          'personal',
          'contact',
          'skills',
          'languages',
          'references',
          'profile',
          'experience',
          'education',
        ],
        sidebarSections: ['contact', 'skills', 'languages', 'references'],
        placements: [
          { sectionId: 'contact', column: 'sidebar', order: 0 },
          { sectionId: 'skills', column: 'sidebar', order: 1 },
          { sectionId: 'languages', column: 'sidebar', order: 2 },
          { sectionId: 'references', column: 'sidebar', order: 3 },
          { sectionId: 'profile', column: 'main', order: 0 },
          { sectionId: 'experience', column: 'main', order: 1 },
          { sectionId: 'education', column: 'main', order: 2 },
        ],
      },
      style: {
        primaryColor: '#2c3848',
        secondaryColor: '#e8edf2',
        accentColor: '#3b82f6',
        backgroundColor: '#ffffff',
        textColor: '#334155',
        fontFamily: 'Arial, sans-serif',
        headerStyle: 'left-aligned',
        sectionDivider: 'line',
        nameSize: 23,
        headingSize: 12.5,
        bodySize: 9.5,
        theme: {
          headerBackground: '#2c3848',
          sidebarBackground: '#e8edf2',
          mainBackground: '#ffffff',
          headingColor: '#2c3848',
          sidebarHeadingColor: '#2c3848',
          textColor: '#334155',
          borderColor: '#2c3848',
          iconColor: '#2c3848',
        },
        typography: {
          name: { family: 'Arial, sans-serif', weight: 800, size: 23, letterSpacing: 1.5, textTransform: 'uppercase' },
          jobTitle: { family: 'Arial, sans-serif', weight: 600, size: 12.5, letterSpacing: 1.5, textTransform: 'uppercase' },
          sectionHeading: { family: 'Arial, sans-serif', weight: 700, size: 12.5, letterSpacing: 1.5, textTransform: 'uppercase' },
          sidebarHeading: { family: 'Arial, sans-serif', weight: 700, size: 12, letterSpacing: 1.5, textTransform: 'uppercase' },
          body: { family: 'Arial, sans-serif', weight: 400, size: 9.5, lineHeight: 1.4 },
          sidebarText: { family: 'Arial, sans-serif', weight: 400, size: 9, lineHeight: 1.35 },
        },
        componentStyle: {
          headingVariant: 'underline',
          bulletStyle: 'dot',
          timeline: true,
          icons: true,
          headerBackground: true,
        },
      },
      sections: [
        { id: 'personal', name: 'Personal Details', description: 'Name and role', repeatable: false },
        { id: 'contact', name: 'CONTACT', description: 'Phone, email, address, website', repeatable: false },
        { id: 'skills', name: 'SKILLS', description: 'Professional competencies', repeatable: false },
        { id: 'languages', name: 'LANGUAGES', description: 'Language fluency', repeatable: false },
        { id: 'references', name: 'REFERENCE', description: 'Professional referees', repeatable: true },
        { id: 'profile', name: 'PROFILE', description: 'Executive career summary', repeatable: false },
        { id: 'experience', name: 'WORK EXPERIENCE', description: 'Career timeline milestones', repeatable: true },
        { id: 'education', name: 'EDUCATION', description: 'Degrees and colleges', repeatable: true },
      ],
      fields: [
        { id: 'fullName', label: 'Full Name', type: 'text', required: true, section: 'personal' },
        { id: 'jobTitle', label: 'Professional Title', type: 'text', required: true, section: 'personal' },
        { id: 'phone', label: 'Phone', type: 'phone', required: true, section: 'contact' },
        { id: 'email', label: 'Email', type: 'email', required: true, section: 'contact' },
        { id: 'address', label: 'Address', type: 'text', required: false, section: 'contact' },
        { id: 'website', label: 'Website', type: 'text', required: false, section: 'contact' },
        { id: 'skillsList', label: 'Skills (one per line)', type: 'textarea', required: false, section: 'skills' },
        { id: 'languagesList', label: 'Languages (one per line)', type: 'textarea', required: false, section: 'languages' },
        { id: 'refName', label: 'Referee Name', type: 'text', required: true, section: 'references' },
        { id: 'refTitle', label: 'Position / Company', type: 'text', required: false, section: 'references' },
        { id: 'refPhone', label: 'Phone', type: 'text', required: false, section: 'references' },
        { id: 'refEmail', label: 'Email', type: 'text', required: false, section: 'references' },
        { id: 'summary', label: 'Profile Summary', type: 'textarea', required: false, section: 'profile' },
        { id: 'company', label: 'Company Name', type: 'text', required: true, section: 'experience' },
        { id: 'role', label: 'Job Role / Title', type: 'text', required: true, section: 'experience' },
        { id: 'expPeriod', label: 'Period (e.g. 2030 - PRESENT)', type: 'text', required: false, section: 'experience' },
        { id: 'bullets', label: 'Key Responsibilities', type: 'textarea', required: false, section: 'experience' },
        { id: 'degree', label: 'Degree Name', type: 'text', required: true, section: 'education' },
        { id: 'school', label: 'School / University & GPA', type: 'textarea', required: true, section: 'education' },
        { id: 'gradYear', label: 'Period / Year', type: 'text', required: false, section: 'education' },
      ],
    },
    defaultSingleton: {
      fullName: 'Richard Sanchez',
      jobTitle: 'Marketing Manager',
      phone: '+123-456-7890',
      email: 'hello@reallygreatsite.com',
      address: '123 Anywhere St., Any City',
      website: 'www.reallygreatsite.com',
      skillsList: 'Project Management\nPublic Relations\nTeamwork\nTime Management\nLeadership\nEffective Communication\nCritical Thinking\nDigital Marketing',
      languagesList: 'English (Fluent)\nFrench (Fluent)\nGerman (Basic)\nSpanish (Intermediate)',
      summary:
        'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam quis nostrud exercitation. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam quis nostrud exercitation.',
    },
    defaultEntries: {
      references: [
        {
          refName: 'Estelle Darcy',
          refTitle: 'Wardiere Inc. / CTO',
          refPhone: 'Phone: 123-456-7890',
          refEmail: 'Email : hello@reallygreatsite.com',
        },
      ],
      experience: [
        {
          company: 'Borcelle Studio',
          role: 'Marketing Manager & Specialist',
          expPeriod: '2030 - PRESENT',
          bullets:
            'Develop and execute comprehensive marketing strategies and campaigns that align with the company’s goals and objectives.\nLead, mentor, and manage a high-performing marketing team, fostering a collaborative and results-driven work environment.\nMonitor brand consistency across marketing channels and materials.',
        },
        {
          company: 'Fauget Studio',
          role: 'Marketing Manager & Specialist',
          expPeriod: '2025 - 2029',
          bullets:
            'Create and manage the marketing budget, ensuring efficient allocation of resources and optimizing ROI.\nOversee market research to identify emerging trends, customer needs, and competitor strategies.',
        },
        {
          company: 'Studio Shodwe',
          role: 'Marketing Manager & Specialist',
          expPeriod: '2024 - 2025',
          bullets:
            'Develop and maintain strong relationships with partners, agencies, and vendors to support marketing initiatives.\nMonitor and maintain brand consistency across all marketing channels and materials.',
        },
      ],
      education: [
        {
          degree: 'Master of Business Management',
          school: 'School of business | Wardiere University\nGPA: 3.8 / 4.0',
          gradYear: '2029 - 2031',
        },
        {
          degree: 'Bachelor of Business Management',
          school: 'School of business | Wardiere University\nGPA: 3.8 / 4.0',
          gradYear: '2025 - 2029',
        },
      ],
    },
  },

  // 5. BLACK WHITE MINIMALIST (Donna Stroupe - Image 3 Right)
  {
    id: 'black-white-minimalist',
    name: 'Black White Minimalist',
    description: 'Dark slate navy sidebar with timeline connecting sales milestones, elegant typography, and clean contrast.',
    badge: 'Clean ATS',
    category: 'Minimalist',
    colorPreview: ['#242e38', '#ffffff', '#0f172a', '#2563eb'],
    analysis: {
      templateName: 'Black White Minimalist',
      description: 'High contrast clean sales resume with connected tree timeline',
      confidence: 0.97,
      layout: {
        type: 'sidebar-left',
        headerPlacement: 'main-column',
        columns: [
          { id: 'sidebar', width: 0.32 },
          { id: 'main', width: 0.68 },
        ],
        photo: {
          included: true,
          position: 'sidebar',
          shape: 'circle',
          size: 'large',
        },
        page: {
          widthMm: 210,
          heightMm: 297,
          margins: { top: 6, right: 7, bottom: 6, left: 7 },
        },
        geometry: {
          orientation: 'portrait',
          sidebarWidth: 0.32,
          mainWidth: 0.68,
          gap: 0,
          verticalGap: 12,
        },
        orderedSections: [
          'personal',
          'contact',
          'education',
          'skills',
          'language',
          'profile',
          'experience',
          'references',
        ],
        sidebarSections: ['contact', 'education', 'skills', 'language'],
        placements: [
          { sectionId: 'contact', column: 'sidebar', order: 0 },
          { sectionId: 'education', column: 'sidebar', order: 1 },
          { sectionId: 'skills', column: 'sidebar', order: 2 },
          { sectionId: 'language', column: 'sidebar', order: 3 },
          { sectionId: 'profile', column: 'main', order: 0 },
          { sectionId: 'experience', column: 'main', order: 1 },
          { sectionId: 'references', column: 'main', order: 2 },
        ],
      },
      style: {
        primaryColor: '#242e38',
        secondaryColor: '#ffffff',
        accentColor: '#1e293b',
        backgroundColor: '#ffffff',
        textColor: '#334155',
        fontFamily: 'Arial, sans-serif',
        headerStyle: 'left-aligned',
        sectionDivider: 'line',
        nameSize: 26,
        headingSize: 13,
        bodySize: 9.5,
        theme: {
          headerBackground: undefined,
          sidebarBackground: '#242e38',
          mainBackground: '#ffffff',
          headingColor: '#1e293b',
          sidebarHeadingColor: '#ffffff',
          textColor: '#334155',
          borderColor: '#1e293b',
          iconColor: '#1e293b',
        },
        typography: {
          name: { family: 'Arial, sans-serif', weight: 800, size: 26, letterSpacing: 1, textTransform: 'none' },
          jobTitle: { family: 'Arial, sans-serif', weight: 600, size: 13, letterSpacing: 1, textTransform: 'none' },
          sectionHeading: { family: 'Arial, sans-serif', weight: 700, size: 13, letterSpacing: 1.5, textTransform: 'uppercase' },
          sidebarHeading: { family: 'Arial, sans-serif', weight: 700, size: 12, letterSpacing: 1.5, textTransform: 'uppercase' },
          body: { family: 'Arial, sans-serif', weight: 400, size: 9.5, lineHeight: 1.4 },
          sidebarText: { family: 'Arial, sans-serif', weight: 400, size: 9, lineHeight: 1.35 },
        },
        componentStyle: {
          headingVariant: 'underline',
          bulletStyle: 'dot',
          timeline: true,
          icons: true,
          headerBackground: false,
        },
      },
      sections: [
        { id: 'personal', name: 'Personal Details', description: 'Name and professional title', repeatable: false },
        { id: 'contact', name: 'Contact', description: 'Phone, email, website', repeatable: false },
        { id: 'education', name: 'Education', description: 'Degrees and colleges', repeatable: true },
        { id: 'skills', name: 'Skills', description: 'Sales and management skills', repeatable: false },
        { id: 'language', name: 'Language', description: 'Language proficiencies', repeatable: false },
        { id: 'profile', name: 'Profile', description: 'Brief introduction', repeatable: false },
        { id: 'experience', name: 'Work Experience', description: 'Sales roles and achievements', repeatable: true },
        { id: 'references', name: 'Reference', description: 'Professional endorsements', repeatable: true },
      ],
      fields: [
        { id: 'fullName', label: 'Full Name', type: 'text', required: true, section: 'personal' },
        { id: 'jobTitle', label: 'Job Title', type: 'text', required: true, section: 'personal' },
        { id: 'phone', label: 'Phone', type: 'phone', required: true, section: 'contact' },
        { id: 'email', label: 'Email', type: 'email', required: true, section: 'contact' },
        { id: 'website', label: 'Website', type: 'text', required: false, section: 'contact' },
        { id: 'degree', label: 'Degree Name', type: 'text', required: true, section: 'education' },
        { id: 'school', label: 'University / Institution', type: 'text', required: true, section: 'education' },
        { id: 'eduDates', label: 'Dates (e.g. 2020 - 2023)', type: 'text', required: false, section: 'education' },
        { id: 'skillsList', label: 'Skills (one per line)', type: 'textarea', required: false, section: 'skills' },
        { id: 'languagesList', label: 'Languages (one per line)', type: 'textarea', required: false, section: 'language' },
        { id: 'intro', label: 'Introductory Statement', type: 'textarea', required: false, section: 'profile' },
        { id: 'role', label: 'Position', type: 'text', required: true, section: 'experience' },
        { id: 'company', label: 'Company', type: 'text', required: true, section: 'experience' },
        { id: 'expDates', label: 'Period (e.g. 2022 - 2025)', type: 'text', required: false, section: 'experience' },
        { id: 'bullets', label: 'Accomplishments', type: 'textarea', required: false, section: 'experience' },
        { id: 'refName', label: 'Full Name & Title', type: 'text', required: true, section: 'references' },
        { id: 'refContact', label: 'Company & Phone', type: 'text', required: false, section: 'references' },
      ],
    },
    defaultSingleton: {
      fullName: 'Donna Stroupe',
      jobTitle: 'Sales Representative',
      phone: '123-456-7890',
      email: 'hello@reallygreatsite.com',
      website: 'www.reallygreatsite.com',
      skillsList: 'Sales Strategies\nNegotiation Skills\nProblem-Solving\nTime Management\nPresentation Skills\nNetworking\nMarket Research\nTeam Collaboration',
      languagesList: 'English (Native)\nGermany (Basic)',
      intro:
        'I am a Sales Representative who initializes and manages relationships with customers. I serve as their point of contact and lead from initial outreach through the making of the final purchase by them or someone in their household.',
    },
    defaultEntries: {
      education: [
        {
          degree: 'Bachelor of Business Management',
          school: 'Borcelle University',
          eduDates: '2020 - 2023',
        },
        {
          degree: 'Bachelor of Business Management',
          school: 'Wardiere University',
          eduDates: '2016 - 2020',
        },
        {
          degree: 'Bachelor of Business Management',
          school: 'Wardiere University',
          eduDates: '2014 - 2018',
        },
      ],
      experience: [
        {
          role: 'Sales Representative',
          company: 'Timmerman Industries',
          expDates: '2022 - 2025',
          bullets:
            'Developed and executed sales strategies, resulting in a 25% increase in annual revenue. Managed a portfolio of 50+ clients, achieving a 95% customer retention rate.\nConducted market research to identify new business opportunities and target prospects.',
        },
        {
          role: 'FMCG Sales Agent',
          company: 'Timmerman Industries',
          expDates: '2020 - 2022',
          bullets:
            'Prospected and qualified leads through cold calling, email campaigns, and networking events.\nIncreased sales by 20% by implementing effective upselling and cross-selling strategies.\nCollaborated with the marketing team to develop targeted sales materials and promotional offers.',
        },
        {
          role: 'FMCG Sales Agent',
          company: 'Timmerman Industries',
          expDates: '2020 - 2022',
          bullets:
            'Maintained up-to-date knowledge of product features and benefits to provide accurate information to clients.\nProvided exceptional customer service, addressing inquiries and resolving issues in a timely manner.',
        },
      ],
      references: [
        {
          refName: 'Harumi Kobayashi',
          refContact: 'Wardiere Inc. / CEO | Phone: 123-456-7890 | Email: hello@reallygreatsite.com',
        },
        {
          refName: 'Bailey Dupont',
          refContact: 'Wardiere Inc. / CEO | Phone: 123-456-7890 | Email: hello@reallygreatsite.com',
        },
      ],
    },
  },

  // 6. NAVY COMPACT CLEAN (Lorna Alvarado - Image 1 Middle)
  {
    id: 'navy-compact-clean',
    name: 'Navy Compact Clean',
    description: 'Deep navy sidebar with round icon badges, bold uppercase typography, and concise about summary.',
    badge: 'Clean ATS',
    category: 'Corporate',
    colorPreview: ['#18314f', '#ffffff', '#18314f', '#0284c7'],
    analysis: {
      templateName: 'Navy Compact Clean',
      description: 'Deep navy sidebar with clean round badge icons',
      confidence: 0.97,
      layout: {
        type: 'sidebar-left',
        headerPlacement: 'main-column',
        columns: [
          { id: 'sidebar', width: 0.32 },
          { id: 'main', width: 0.68 },
        ],
        photo: {
          included: true,
          position: 'sidebar',
          shape: 'circle',
          size: 'large',
        },
        page: {
          widthMm: 210,
          heightMm: 297,
          margins: { top: 6, right: 7, bottom: 6, left: 7 },
        },
        geometry: {
          orientation: 'portrait',
          sidebarWidth: 0.32,
          mainWidth: 0.68,
          gap: 0,
          verticalGap: 12,
        },
        orderedSections: [
          'personal',
          'contact',
          'education',
          'skills',
          'language',
          'profile',
          'experience',
          'references',
        ],
        sidebarSections: ['contact', 'education', 'skills', 'language'],
        placements: [
          { sectionId: 'contact', column: 'sidebar', order: 0 },
          { sectionId: 'education', column: 'sidebar', order: 1 },
          { sectionId: 'skills', column: 'sidebar', order: 2 },
          { sectionId: 'language', column: 'sidebar', order: 3 },
          { sectionId: 'profile', column: 'main', order: 0 },
          { sectionId: 'experience', column: 'main', order: 1 },
          { sectionId: 'references', column: 'main', order: 2 },
        ],
      },
      style: {
        primaryColor: '#18314f',
        secondaryColor: '#f1f5f9',
        accentColor: '#0284c7',
        backgroundColor: '#ffffff',
        textColor: '#334155',
        fontFamily: 'Arial, sans-serif',
        headerStyle: 'left-aligned',
        sectionDivider: 'line',
        nameSize: 26,
        headingSize: 13,
        bodySize: 9.5,
        theme: {
          headerBackground: undefined,
          sidebarBackground: '#18314f',
          mainBackground: '#ffffff',
          headingColor: '#18314f',
          sidebarHeadingColor: '#ffffff',
          textColor: '#334155',
          borderColor: '#18314f',
          iconColor: '#18314f',
        },
        typography: {
          name: { family: 'Arial, sans-serif', weight: 900, size: 26, letterSpacing: 1.5, textTransform: 'uppercase' },
          jobTitle: { family: 'Arial, sans-serif', weight: 600, size: 13, letterSpacing: 1.2, textTransform: 'none' },
          sectionHeading: { family: 'Arial, sans-serif', weight: 700, size: 13, letterSpacing: 1.5, textTransform: 'uppercase' },
          sidebarHeading: { family: 'Arial, sans-serif', weight: 700, size: 12, letterSpacing: 1.5, textTransform: 'uppercase' },
          body: { family: 'Arial, sans-serif', weight: 400, size: 9.5, lineHeight: 1.4 },
          sidebarText: { family: 'Arial, sans-serif', weight: 400, size: 9, lineHeight: 1.35 },
        },
        componentStyle: {
          headingVariant: 'underline',
          bulletStyle: 'dot',
          timeline: true,
          icons: true,
          headerBackground: false,
        },
      },
      sections: [
        { id: 'personal', name: 'Personal Details', description: 'Name and role', repeatable: false },
        { id: 'contact', name: 'Contact', description: 'Phone, email, address', repeatable: false },
        { id: 'education', name: 'Education', description: 'Universities and programs', repeatable: true },
        { id: 'skills', name: 'Skills', description: 'Core skills', repeatable: false },
        { id: 'language', name: 'Language', description: 'Languages spoken', repeatable: false },
        { id: 'profile', name: 'About Me', description: 'Personal introduction', repeatable: false },
        { id: 'experience', name: 'Experience', description: 'Career achievements', repeatable: true },
        { id: 'references', name: 'References', description: 'Executive references', repeatable: true },
      ],
      fields: [
        { id: 'fullName', label: 'Full Name', type: 'text', required: true, section: 'personal' },
        { id: 'jobTitle', label: 'Job Title', type: 'text', required: true, section: 'personal' },
        { id: 'phone', label: 'Phone', type: 'phone', required: true, section: 'contact' },
        { id: 'email', label: 'Email', type: 'email', required: true, section: 'contact' },
        { id: 'address', label: 'Address', type: 'text', required: false, section: 'contact' },
        { id: 'degree', label: 'Degree / Program', type: 'text', required: true, section: 'education' },
        { id: 'university', label: 'University', type: 'text', required: true, section: 'education' },
        { id: 'eduDates', label: 'Period (e.g. 2016 - 2020)', type: 'text', required: false, section: 'education' },
        { id: 'skillsList', label: 'Skills (one per line)', type: 'textarea', required: false, section: 'skills' },
        { id: 'languagesList', label: 'Languages (one per line)', type: 'textarea', required: false, section: 'language' },
        { id: 'aboutText', label: 'About Me Summary', type: 'textarea', required: false, section: 'profile' },
        { id: 'role', label: 'Position', type: 'text', required: true, section: 'experience' },
        { id: 'company', label: 'Company', type: 'text', required: true, section: 'experience' },
        { id: 'expDates', label: 'Dates (e.g. 2018 - 2020)', type: 'text', required: false, section: 'experience' },
        { id: 'desc', label: 'Responsibilities', type: 'textarea', required: false, section: 'experience' },
        { id: 'refName', label: 'Referee Name', type: 'text', required: true, section: 'references' },
        { id: 'refInfo', label: 'Company & Phone', type: 'text', required: false, section: 'references' },
      ],
    },
    defaultSingleton: {
      fullName: 'Lorna Alvarado',
      jobTitle: 'Sales Representative',
      phone: '123-456-7890',
      email: 'hello@reallygreatsite.com',
      address: '123 Anywhere St., Any City',
      skillsList: 'Management Skills\nCreativity\nDigital Marketing\nNegotiation\nCritical Thinking\nLeadership',
      languagesList: 'English (Fluent)\nSpain (Native)',
      aboutText:
        'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
    },
    defaultEntries: {
      education: [
        {
          degree: 'Bachelor of Business Management',
          university: 'Borcelle University',
          eduDates: '2020 - 2023',
        },
        {
          degree: 'Bachelor of Business Management',
          university: 'Wardiere University',
          eduDates: '2016 - 2020',
        },
        {
          degree: 'Bachelor of Business Management',
          university: 'Borcelle University',
          eduDates: '2012 - 2016',
        },
      ],
      experience: [
        {
          role: 'Product Design Manager',
          company: 'Arowwai Industries',
          expDates: '2018 - 2020',
          desc: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc sit amet sem nec risus egestas accumsan. In enim nunc, tincidunt ut quam eget, luctus sollicitudin neque.',
        },
        {
          role: 'Marketing Manager',
          company: 'Arowwai Industries',
          expDates: '2019 - 2020',
          desc: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc sit amet sem nec risus egestas accumsan. In enim nunc, tincidunt ut quam eget, luctus sollicitudin neque.',
        },
        {
          role: 'Marketing Manager',
          company: 'Arowwai Industries',
          expDates: '2017 - 2019',
          desc: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc sit amet sem nec risus egestas accumsan. In enim nunc, tincidunt ut quam eget, luctus sollicitudin neque.',
        },
      ],
      references: [
        {
          refName: 'Harumi Kobayashi',
          refInfo: 'Wardiere Inc. / CEO | Phone: 123-456-7890 | Email: hello@reallygreatsite.com',
        },
        {
          refName: 'Bailey Dupont',
          refInfo: 'Wardiere Inc. / CEO | Phone: 123-456-7890 | Email: hello@reallygreatsite.com',
        },
      ],
    },
  },
  // 7. ACADEMIC GRADUATE (Two-Column Maqaa Kee/Your Name format)
  {
    id: 'academic-graduate',
    name: 'Academic Graduate (Two-Column)',
    description: 'Traditional academic two-column CV for graduates and engineers with bold underlined headings, technical proficiencies, and projects.',
    badge: 'Academic',
    category: 'Academic',
    colorPreview: ['#0f172a', '#ffffff', '#1e3a8a', '#334155'],
    analysis: {
      templateName: 'Academic Graduate',
      description: 'Formal two-column academic CV with underlined headings and technical skills',
      confidence: 0.98,
      layout: {
        type: 'two-column',
        headerPlacement: 'top-full-width',
        hideInlineHeader: true,
        columns: [
          { id: 'main-left', width: 0.54 },
          { id: 'main-right', width: 0.46 },
        ],
        photo: {
          included: false,
          position: 'top-left',
          shape: 'square',
          size: 'small',
        },
        page: {
          widthMm: 210,
          heightMm: 297,
          margins: { top: 7, right: 8, bottom: 7, left: 8 },
        },
        geometry: {
          orientation: 'portrait',
          mainWidth: 0.54,
          gap: 16,
          verticalGap: 10,
        },
        orderedSections: [
          'personalInfo',
          'summary',
          'projects',
          'technicalSkills',
          'personnelSkills',
          'languages',
          'hobbies',
          'education',
          'experience',
          'references',
        ],
        placements: [
          { sectionId: 'personalInfo', column: 'main-left', order: 0 },
          { sectionId: 'summary', column: 'main-left', order: 1 },
          { sectionId: 'projects', column: 'main-left', order: 2 },
          { sectionId: 'technicalSkills', column: 'main-right', order: 0 },
          { sectionId: 'personnelSkills', column: 'main-right', order: 1 },
          { sectionId: 'languages', column: 'main-right', order: 2 },
          { sectionId: 'hobbies', column: 'main-right', order: 3 },
          { sectionId: 'education', column: 'main-right', order: 4 },
          { sectionId: 'experience', column: 'main-right', order: 5 },
          { sectionId: 'references', column: 'main-right', order: 6 },
        ],
      },
      style: {
        primaryColor: '#0f172a',
        secondaryColor: '#ffffff',
        accentColor: '#1e3a8a',
        backgroundColor: '#ffffff',
        textColor: '#111827',
        fontFamily: 'Georgia, serif',
        headerStyle: 'left-aligned',
        sectionDivider: 'line',
        nameSize: 18,
        headingSize: 12,
        bodySize: 9,
        theme: {
          mainBackground: '#ffffff',
          sidebarBackground: '#ffffff',
          headingColor: '#0f172a',
          textColor: '#111827',
          borderColor: '#0f172a',
          iconColor: '#0f172a',
        },
        typography: {
          name: { family: 'Georgia, serif', weight: 800, size: 16, letterSpacing: 0.5, textTransform: 'uppercase' },
          jobTitle: { family: 'Georgia, serif', weight: 600, size: 11, letterSpacing: 0.5, textTransform: 'none' },
          sectionHeading: { family: 'Georgia, serif', weight: 800, size: 12, letterSpacing: 0.5, textTransform: 'uppercase' },
          sidebarHeading: { family: 'Georgia, serif', weight: 800, size: 12, letterSpacing: 0.5, textTransform: 'uppercase' },
          body: { family: 'Georgia, serif', weight: 400, size: 9, lineHeight: 1.35 },
          sidebarText: { family: 'Georgia, serif', weight: 400, size: 9, lineHeight: 1.35 },
        },
        componentStyle: {
          headingVariant: 'underline',
          bulletStyle: 'dot',
          timeline: false,
          icons: false,
          headerBackground: false,
        },
      },
      sections: [
        { id: 'personalInfo', name: 'CURRICULUM VITAE (CV)', description: 'Personal header details', repeatable: false },
        { id: 'summary', name: 'SUMMARY', description: 'Career profile and objective', repeatable: false },
        { id: 'projects', name: 'PROJECTS', description: 'Academic and final year software projects', repeatable: true },
        { id: 'technicalSkills', name: 'TECHNICAL SKILLS', description: 'Programming, web, databases, tools', repeatable: false },
        { id: 'personnelSkills', name: 'PERSONNEL SKILLS', description: 'Soft skills and teamwork attributes', repeatable: false },
        { id: 'languages', name: 'LANGUAGES', description: 'Spoken languages', repeatable: false },
        { id: 'hobbies', name: 'HOBBIES', description: 'Interests and activities', repeatable: false },
        { id: 'education', name: 'Educational Background', description: 'Academic degree and CGPA', repeatable: true },
        { id: 'experience', name: 'EXPERIENCE', description: 'Practical work history', repeatable: true },
        { id: 'references', name: 'REFERENCE', description: 'Academic and professional referees', repeatable: true },
      ],
      fields: [
        { id: 'fullName', label: 'Name', type: 'text', required: true, section: 'personalInfo' },
        { id: 'field', label: 'Field', type: 'text', required: true, section: 'personalInfo' },
        { id: 'phone', label: 'Phone No', type: 'phone', required: true, section: 'personalInfo' },
        { id: 'email', label: 'Email', type: 'email', required: true, section: 'personalInfo' },
        { id: 'summaryText', label: 'Summary Statement', type: 'textarea', required: true, section: 'summary' },
        { id: 'projectName', label: 'Project Name & Category', type: 'text', required: true, section: 'projects' },
        { id: 'projectDesc', label: 'Outcomes & Tools (one per line)', type: 'textarea', required: true, section: 'projects' },
        { id: 'techSkillsText', label: 'Technical Categories (one per line)', type: 'textarea', required: true, section: 'technicalSkills' },
        { id: 'softSkillsText', label: 'Personal Skills (one per line)', type: 'textarea', required: true, section: 'personnelSkills' },
        { id: 'langText', label: 'Languages (one per line)', type: 'textarea', required: true, section: 'languages' },
        { id: 'hobbyText', label: 'Hobbies (one per line)', type: 'textarea', required: false, section: 'hobbies' },
        { id: 'degree', label: 'Degree Name', type: 'text', required: true, section: 'education' },
        { id: 'institution', label: 'University / Institution', type: 'text', required: true, section: 'education' },
        { id: 'cgpa', label: 'CGPA / Grade', type: 'text', required: false, section: 'education' },
        { id: 'exitExam', label: 'Exit Exam / Honors', type: 'text', required: false, section: 'education' },
        { id: 'company', label: 'Organization / Company', type: 'text', required: true, section: 'experience' },
        { id: 'role', label: 'Position', type: 'text', required: true, section: 'experience' },
        { id: 'duration', label: 'Duration / Period', type: 'text', required: false, section: 'experience' },
        { id: 'refName', label: 'Name', type: 'text', required: true, section: 'references' },
        { id: 'refPhone', label: 'Phone', type: 'text', required: false, section: 'references' },
        { id: 'refPosition', label: 'Position / Department', type: 'text', required: false, section: 'references' },
      ],
    },
    defaultSingleton: {
      fullName: 'Your Name / Maqaa Kee',
      field: 'Software Engineering',
      phone: '+251912345678',
      email: 'yourname@example.com',
      summaryText:
        'I am a dedicated Software Engineering graduate from ABC University with a CGPA of 4 and an exit exam score of 99%. I possess strong technical skills in Java, C++, C, Android, React, and web development technologies, along with experience in managing both SQL and NoSQL databases. I am currently enhancing my expertise in full-stack development using the MERN (MongoDB, Express, React, Node.js) stack. During my internship at ABC Company, I gained practical experience in software development, database management, and data analysis.\n\nI am a quick learner with strong problem-solving, adaptability, and teamwork skills. I am eager to contribute to innovative projects where I can apply my knowledge and grow as a software engineer.',
      techSkillsText:
        'Programming Languages: Java, C++, C, JavaScript, PHP.\nWeb Technologies: HTML, CSS, React.js, Node.js, Express.js.\nDatabases: MySQL, MongoDB\nFrameworks & Tools: Android Studio, Git, VS Code.',
      softSkillsText: 'Adaptability\nCommunication\nTeamwork and Collaboration',
      langText: 'Afaan Oromo Native\nAmharic Fluent\nEnglish Fluent',
      hobbyText: 'Reading\nCoding\nWatching Movies',
    },
    defaultEntries: {
      projects: [
        {
          projectName: '1. Employee Hiring System for ABC University (Final Year Project)',
          projectDesc:
            'Developed a web-based system to automate the employee hiring process.\nDesigned features to continuously monitor applicants, evaluate candidates based on university criteria, and back up selected candidate data.\nTools used: PHP, MySQL, HTML, CSS, JavaScript.',
        },
        {
          projectName: '2. House Rental System for Bule Hora City (Internship Project)',
          projectDesc:
            'Built a web-based platform that facilitates property listing and rental services for users in Bule Hora City.',
        },
      ],
      education: [
        {
          degree: 'BSc in Software Engineering',
          institution: 'ABC University',
          cgpa: 'CGPA: 4 / 4.00',
          exitExam: 'Exit Exam Result: 99%',
        },
      ],
      experience: [
        {
          company: 'ABC Company',
          role: 'Position: IT expert',
          duration: 'Duration: 1 year and 2+ Months',
        },
      ],
      references: [
        {
          refName: 'Abebe Bekele',
          refPhone: 'Phone: +251911223344',
          refPosition: 'Position: Head, Department of Software Engineering.',
        },
      ],
    },
  },

  // 8. AZURE WAVE MARKETER (Mark Jones - Creative Ocean Wave)
  {
    id: 'azure-wave',
    name: 'Azure Wave Marketer',
    description: 'Ocean-blue curved header badge, ice-blue sidebar with square bullet skills & affiliations, and crisp clean main column with employment highlights.',
    badge: 'Trending',
    category: 'Creative',
    colorPreview: ['#1d78c1', '#eef6fc', '#1d78c1', '#1e293b'],
    analysis: {
      templateName: 'Azure Wave Marketer',
      description: 'Ocean blue wave header badge and ice blue sidebar layout with square bullet skills',
      confidence: 0.99,
      layout: {
        type: 'sidebar-left',
        headerPlacement: 'sidebar-top',
        columns: [
          { id: 'sidebar', width: 0.33 },
          { id: 'main', width: 0.67 },
        ],
        photo: {
          included: false,
          position: 'sidebar',
          shape: 'circle',
          size: 'medium',
        },
        page: {
          widthMm: 210,
          heightMm: 297,
          margins: { top: 6, right: 7, bottom: 6, left: 7 },
        },
        geometry: {
          orientation: 'portrait',
          sidebarWidth: 0.33,
          mainWidth: 0.67,
          gap: 0,
          verticalGap: 11,
          columnTopPad: 0,
        },
        orderedSections: [
          'personal',
          'contact',
          'skills',
          'affiliations',
          'hobbies',
          'profile',
          'experience',
          'education',
          'certifications',
        ],
        sidebarSections: ['contact', 'skills', 'affiliations', 'hobbies'],
        placements: [
          { sectionId: 'contact', column: 'sidebar', order: 0 },
          { sectionId: 'skills', column: 'sidebar', order: 1 },
          { sectionId: 'affiliations', column: 'sidebar', order: 2 },
          { sectionId: 'hobbies', column: 'sidebar', order: 3 },
          { sectionId: 'profile', column: 'main', order: 0 },
          { sectionId: 'experience', column: 'main', order: 1 },
          { sectionId: 'education', column: 'main', order: 2 },
          { sectionId: 'certifications', column: 'main', order: 3 },
        ],
      },
      style: {
        primaryColor: '#1d78c1',
        secondaryColor: '#eef6fc',
        accentColor: '#1d78c1',
        backgroundColor: '#ffffff',
        textColor: '#1e293b',
        fontFamily: 'Arial, sans-serif',
        headerStyle: 'left-aligned',
        sectionDivider: 'line',
        nameSize: 20,
        headingSize: 13.5,
        bodySize: 9.3,
        theme: {
          headerBackground: '#1d78c1',
          sidebarBackground: '#eef6fc',
          mainBackground: '#ffffff',
          headingColor: '#1d78c1',
          sidebarHeadingColor: '#1d78c1',
          textColor: '#1e293b',
          borderColor: '#1d78c1',
          iconColor: '#1d78c1',
        },
        typography: {
          name: { family: 'Arial, sans-serif', weight: 800, size: 20, letterSpacing: 0.5, textTransform: 'none' },
          jobTitle: { family: 'Arial, sans-serif', weight: 700, size: 12.5, letterSpacing: 0, textTransform: 'none' },
          sectionHeading: { family: 'Arial, sans-serif', weight: 700, size: 13.5, letterSpacing: 0, textTransform: 'none' },
          sidebarHeading: { family: 'Arial, sans-serif', weight: 700, size: 13.5, letterSpacing: 0, textTransform: 'none' },
          body: { family: 'Arial, sans-serif', weight: 400, size: 9.3, lineHeight: 1.38 },
          sidebarText: { family: 'Arial, sans-serif', weight: 400, size: 9.1, lineHeight: 1.34 },
        },
        componentStyle: {
          headingVariant: 'underline',
          bulletStyle: 'square',
          timeline: false,
          icons: false,
          headerBackground: true,
        },
      },
      sections: [
        { id: 'personal', name: 'Personal Details', description: 'Name and title', repeatable: false },
        { id: 'contact', name: 'Personal details', description: 'Phone, email, address, website', repeatable: false },
        { id: 'skills', name: 'Skills', description: 'Key marketing and technical skills', repeatable: false },
        { id: 'affiliations', name: 'Professional Affiliations', description: 'Industry associations and memberships', repeatable: true },
        { id: 'hobbies', name: 'Hobbies', description: 'Personal projects and achievements', repeatable: false },
        { id: 'profile', name: 'Profile', description: 'Summary headline and narrative', repeatable: false },
        { id: 'experience', name: 'Employment', description: 'Work experience and accomplishments', repeatable: true },
        { id: 'education', name: 'Education', description: 'Academic degrees and modules', repeatable: true },
        { id: 'certifications', name: 'Certificates', description: 'Professional courses and certificates', repeatable: true },
      ],
      fields: [
        { id: 'fullName', label: 'Full Name', type: 'text', required: true, section: 'personal' },
        { id: 'email', label: 'Email Address', type: 'email', required: true, section: 'contact' },
        { id: 'phone', label: 'Phone', type: 'phone', required: true, section: 'contact' },
        { id: 'address', label: 'Address', type: 'text', required: false, section: 'contact' },
        { id: 'website', label: 'Website', type: 'text', required: false, section: 'contact' },
        { id: 'skillsList', label: 'Skills (one per line with Title: Description)', type: 'textarea', required: false, section: 'skills' },
        { id: 'affilName', label: 'Affiliation / Title', type: 'text', required: true, section: 'affiliations' },
        { id: 'affilDate', label: 'Period / Date', type: 'text', required: false, section: 'affiliations' },
        { id: 'hobbiesList', label: 'Hobbies (one per line)', type: 'textarea', required: false, section: 'hobbies' },
        { id: 'headline', label: 'Headline', type: 'text', required: true, section: 'profile' },
        { id: 'summary', label: 'Professional Summary', type: 'textarea', required: true, section: 'profile' },
        { id: 'role', label: 'Position / Role', type: 'text', required: true, section: 'experience' },
        { id: 'company', label: 'Company, Location', type: 'text', required: true, section: 'experience' },
        { id: 'expPeriod', label: 'Period (e.g. Jan 2018 - Present)', type: 'text', required: false, section: 'experience' },
        { id: 'responsibilities', label: 'Responsibilities & Achievements (one per line)', type: 'textarea', required: false, section: 'experience' },
        { id: 'degree', label: 'Degree / Program', type: 'text', required: true, section: 'education' },
        { id: 'institution', label: 'University, Location', type: 'text', required: true, section: 'education' },
        { id: 'eduYear', label: 'Period / Year', type: 'text', required: false, section: 'education' },
        { id: 'eduModules', label: 'Modules & Coursework', type: 'textarea', required: false, section: 'education' },
        { id: 'certName', label: 'Certificate Name', type: 'text', required: true, section: 'certifications' },
        { id: 'certDate', label: 'Date Earned', type: 'text', required: false, section: 'certifications' },
        { id: 'certDesc', label: 'Modules & Topics (one per line)', type: 'textarea', required: false, section: 'certifications' },
      ],
    },
    defaultSingleton: {
      fullName: 'Mark Jones',
      email: 'mark_jones@example.com',
      phone: '+44 76345 346245',
      address: '20 West Street\nBN1 6LR Brighton',
      website: 'markjones.com',
      skillsList:
        'Website redesign: Led website redesign project to increase traffic by 50%.\nContent management systems: Posted marketing copy to company site using Craft CMS.\nAnalytics: Optimised company website to increase time-on-page by analysing data reports on page performances.\nSocial media: Managed the company\'s social media accounts, averaging a 20-percent follower growth across all platforms.\nCommunication: Cultivated working relationships with clients through recreational business meetings.',
      hobbiesList:
        'Write 4 articles on self-development on Medium per month, averaging 1,000 likes for each article and earning £1,000 in total.',
      headline:
        'Results-Focused Content Marketer with Experience Leading £1M Large-Scale Website Project',
      summary:
        'As a results-focused content marketer with 9+ years’ experience, managing blog content, website projects and social media. Led £1M large-scale web redesign project, affecting 1, 000 pages. Achieved 50% increase in organic traffic, after implementing SEO and audit recommendations. Familiar with Salesforce and MailChimp.',
    },
    defaultEntries: {
      affiliations: [
        {
          affilName: 'Chartered Institute of Marketing (Associate ACIM)',
          affilDate: 'Apr 2018 - Present',
        },
      ],
      experience: [
        {
          role: 'Content Marketing Lead',
          company: 'Pipedrive, London',
          expPeriod: 'Jan 2018 - Present',
          responsibilities:
            'Led £1M large-scale web redesign project, affecting 1, 000 pages.\nAchieved 50% increase in organic traffic to 25,000 visitors monthly, after implementing SEO and content fixes.\nTrained junior team members on web content best practices.',
        },
        {
          role: 'Content Marketer',
          company: 'Abacus Marketing, London',
          expPeriod: 'Aug 2014 - Dec 2018',
          responsibilities:
            'Wrote 4 blog posts monthly on marketing topics to drive brand awareness and website traffic.\nCollected customer data and analysed interactions and website traffic to improve blog conversion rates by 10%.\nGarnered 5,000 likes for a Facebook campaign, promoting the local homeless shelter.',
        },
        {
          role: 'Marketing Assistant',
          company: '121 Marketing, Leeds',
          expPeriod: 'Sep 2012 - Jul 2014',
          responsibilities:
            'Managed the company’s marketing podcast.\nCreated a series of short YouTube videos to promote brand awareness.\nImproved the open rate for the company’s e-mail newsletters by 20% through effective copy.',
        },
      ],
      education: [
        {
          degree: 'Marketing Communications (BA Hons): 1st class',
          institution: 'University of Bournemouth, Bournemouth',
          eduYear: 'Sep 2008 - Jul 2012',
          eduModules:
            'Modules included: principles of marketing and marketing communications, digital technologies, content creation and principles of branding.',
        },
      ],
      certifications: [
        {
          certName: 'Google Digital Garage: The Fundamentals of Digital Marketing',
          certDate: 'Jan 2019',
          certDesc:
            'Modules included: analytics and data insights, business strategy, content marketing, display advertising, e-commerce, e-mail, SEO, SEM and SoMe.',
        },
      ],
    },
  },
];
